### ISSUE TITLE
Problem with rgbd data generation

### ISSUE THREAD

**Issue by paolotron** [THU-VCLab/Part-Guided-3D-RL-for-Sim2Real-Articulated-Object-Manipulation#1]
When I run the command for the rgbd dataset generation
```
python arti_mani/algorithms/data_process/gen_rgbd_data.py 
```
it returns the error
```
gym.error.UnregisteredEnv: No registered env with id: CabinetDoor-v0
```
It makes sense as no gym environments were previously registered, could you explain how to use the script?

**Comment by xspkwy** [comment]
Acually I register the envs in [@register_gym_env("CabinetDoor-v0", max_episode_steps=200)](https://github.com/THU-VCLab/Part-Guided-3D-RL-for-Sim2Real-Articulated-Object-Manipulation/blob/95ae7b4369288c1d3e29d4038fcbeee4bcf2495b/arti_mani/envs/floating_robotiqenv.py#L291), similar with other envs (CabinetDrawer-v0, Faucet-v0).
So you can try to add `from arti_mani.envs.floating_robotiqenv from *` in `gen_rgbd_data.py `.
Also, I will reimplent the project these days, and can check the problems then.
