### ISSUE TITLE
No textures provided

### ISSUE THREAD

**Issue by paolotron** [THU-VCLab/Part-Guided-3D-RL-for-Sim2Real-Articulated-Object-Manipulation#2]
In the _floating_robotiqenv.py_ file when creating the[ FloatingRobotiqEnv object](https://github.com/THU-VCLab/Part-Guided-3D-RL-for-Sim2Real-Articulated-Object-Manipulation/blob/95ae7b4369288c1d3e29d4038fcbeee4bcf2495b/arti_mani/envs/floating_robotiqenv.py#L65), the texture files are required, unfortunately, the _arti_mani/assets/textures_ folder doesn't exist and there are no textures inside the provided dataset. Could you provide the missing files?

**Comment by xspkwy** [comment]
I commit the all files.
Reference:
1. Textures: https://www.robots.ox.ac.uk/~vgg/data/dtd/
2. Random RGBD background images: 
SUN-RGBD: https://rgbd.cs.princeton.edu/, 
SceneNetRGBD: https://robotvault.bitbucket.io/scenenet-rgbd.html

**Comment by xspkwy** [comment]
Done
