### ISSUE TITLE
No file named fixed_cabinet_doors_new.yml

### ISSUE THREAD

**Issue by Charlie0257** [THU-VCLab/Part-Guided-3D-RL-for-Sim2Real-Articulated-Object-Manipulation#3]
Hi, @xspkwy 

Thanks for this great work:)

When I try to run the command `python arti_mani/algorithms/data_process/gen_rgbd_data.py`, there is an error occurring——
`FileNotFoundError: [Errno 2] No such file or directory: '/home/charlie/PycharmProjects/Part-Guided-3D-RL-for-Sim2Real-Articulated-Object-Manipulation/arti_mani/assets/partnet_mobility_configs/fixed_cabinet_doors_new.yml'`

Could you upload the corresponding file?

In addition, could you upload the results of pre-trained data or checkpoints of models to this project?

Best,
Charlie

**Comment by xspkwy** [comment]
Thanks for your concern. 
I update the files you want. 
You may test the pretrained checkpoints follow the examples in `arti_mani/test/real_exps/SB3_opencabinet.py`.

**Comment by Charlie0257** [comment]
Thanks for providing the checkpoints and yml files.

But the current version code is still hard to run:(

Whether I run `arti_mani/algorithms/data_process/gen_rgbd_data.py` or `arti_mani/algorithms/rl_iam/sac_train_segpts_PNfeat.p`, I get a series of errors.

Could you debug this project and refine the readme?

**Comment by xspkwy** [comment]
Thanks for your comments. Actually I cleared more things than I think when upload the project.
Now I reimplement the project and solve the bugs you mentioned.
You can try it again.

**Comment by xspkwy** [comment]
Done

**Comment by Charlie0257** [comment]
Thanks for your help :)
