### ISSUE TITLE
How to install impedance_control?

### ISSUE THREAD

**Issue by Charlie0257** [THU-VCLab/Part-Guided-3D-RL-for-Sim2Real-Articulated-Object-Manipulation#5]
Hi, @xspkwy 
Thanks for your great work!

When I tried sim2real like your project, I didn't know how to install `impedance_control` shown in `xmate3Robotiq.py`.
```
from impedance_control.msg import (
    CartesianControlCommand,
    ImpedanceRobotState,
    JointControlCommand,
)
```
Thanks for any help!

Best,
Charlie

**Comment by xspkwy** [comment]
Well, our real experiments are implemented on a Xmate3 pro arm, and the related controller ros packages are provided by ROKAE Corp.
You may use your own real robotic arm ros controller and replace the corresponding codes.

**Comment by Charlie0257** [comment]
Thanks for your advice:)
